[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/pedido"
  to   = "/.netlify/functions/pedido"
  status = 200

[[redirects]]
  from = "/api/createPreference"
  to   = "/.netlify/functions/createPreference"
  status = 200
