[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]
  [[headers]]
  for = "/pedido_local.html"
  [headers.values]
    Basic-Auth = "local:Rhodes2025!"
    Cache-Control = "no-store"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"


